# Generated by Django 5.0.2 on 2024-03-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thechildrenofcorn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminaccount',
            name='name',
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
