# Generated by Django 5.0.2 on 2024-03-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thechildrenofcorn', '0002_adminaccounts_remove_adminaccount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaccounts',
            name='email',
        ),
        migrations.AddField(
            model_name='adminaccounts',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
